function Terms() {
    return (
        <div style={{ padding: '40px', maxWidth: '800px', margin: '0 auto', color: 'var(--text-main)', lineHeight: '1.7' }}>
            <h1>Terms of Service</h1>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>Last updated: January 2026</p>

            <section>
                <h2>1. Introduction</h2>
                <p>
                    Welcome to SocialFlow Studio. By accessing our website and using our tools
                    (Resizer, Slug Generator, and others), you agree to be bound by these
                    Terms of Service.
                </p>
            </section>

            <section>
                <h2>2. Use of Services</h2>
                <p>
                    Our tools are provided for personal and commercial use. You agree not to
                    use our services for any illegal purposes or to abuse our infrastructure.
                </p>
            </section>

            <section>
                <h2>3. Intellectual Property</h2>
                <p>
                    The content generated by you using our tools belongs to you. The design
                    and code of this website are owned by SocialFlow Studio.
                </p>
            </section>

            <section>
                <h2>4. Disclaimer</h2>
                <p>
                    The services are provided &ldquo;as is&rdquo;. We make no warranties
                    regarding the uptime or accuracy of the tools.
                </p>
            </section>

            <section>
                <h2>5. Termination</h2>
                <p>
                    We reserve the right to terminate access to our services if you violate
                    these terms.
                </p>
            </section>

            <section>
                <h2>6. Contact</h2>
                <p>
                    For questions about these terms, reach out to us at{' '}
                    <a href="mailto:skmudassir.it@gmail.com" style={{ color: 'var(--primary)' }}>
                        skmudassir.it@gmail.com
                    </a>
                    .
                </p>
            </section>
        </div>
    )
}

export default Terms
