function Terms() {
    return (
        <div style={{ padding: '40px', maxWidth: '800px', margin: '0 auto', color: 'var(--text-main)' }}>
            <h1>Terms of Service</h1>
            <p>Last updated: {new Date().toLocaleDateString()}</p>

            <h3>1. Introduction</h3>
            <p>Welcome to SocialFlow Studio. By accessing our website and using our tools (Resizer, Slug Generator, etc.), you agree to be bound by these Terms of Service.</p>

            <h3>2. Use of Services</h3>
            <p>Our tools are provided for personal and commercial use. You agree not to use our services for any illegal purposes or to abuse our infrastructure.</p>

            <h3>3. Intellectual Property</h3>
            <p>The content generated by you using our tools belongs to you. The design and code of this website are owned by SocialFlow Studio.</p>

            <h3>4. Disclaimer</h3>
            <p>The services are provided "as is". We make no warranties regarding the uptime or accuracy of the tools.</p>

            <h3>5. Termination</h3>
            <p>We reserve the right to terminate access to our services if you violate these terms.</p>
        </div>
    )
}

export default Terms
