import { useState } from 'react'
import WidgetPalette from './components/WidgetPalette'
import WidgetCard from './components/WidgetCard'
import ReportToolbar from './components/ReportToolbar'
import { WIDGET_TYPES } from './data/reportData'
import './styles.css'

const STORAGE_KEY = 'reportStudio_savedReport'

function getMonthName() {
    return new Date().toLocaleString('default', { month: 'long' })
}

function generateHtmlReport(title, widgets) {
    const widgetList = widgets
        .map((w, i) => `<li style="margin-bottom:8px">${w.label || w.name || `Widget ${i + 1}`}</li>`)
        .join('')
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
        body { font-family: system-ui, sans-serif; max-width: 700px; margin: 2rem auto; padding: 0 1rem; color: #1a1a2e; background: #f8fafc; }
        h1 { color: #3b82f6; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; }
        .meta { color: #64748b; font-size: 0.9rem; }
        ul { list-style: none; padding: 0; }
        li { background: white; padding: 12px 16px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
        footer { margin-top: 2rem; font-size: 0.8rem; color: #94a3b8; text-align: center; }
    </style>
</head>
<body>
    <h1>${title}</h1>
    <p class="meta">Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
    <h3>Widgets (${widgets.length})</h3>
    <ul>${widgetList}</ul>
    <footer>Report generated by Report Studio</footer>
</body>
</html>`
}

function ReportStudio() {
    const monthName = getMonthName()
    const [title] = useState(`Monthly Report - ${monthName}`)

    // Initial state: Pre-load with "Monthly Overview"
    const [widgets, setWidgets] = useState(() => {
        try {
            const saved = localStorage.getItem(STORAGE_KEY)
            if (saved) return JSON.parse(saved)
        } catch { /* ignore parse errors */ }
        return [
            { ...(WIDGET_TYPES.find(w => w.id === 'w_engagement')), uniqueId: 1 },
            { ...(WIDGET_TYPES.find(w => w.id === 'w_revenue')), uniqueId: 2 },
            { ...(WIDGET_TYPES.find(w => w.id === 'w_followers')), uniqueId: 3 },
            { ...(WIDGET_TYPES.find(w => w.id === 'w_top_posts')), uniqueId: 4 }
        ]
    })

    const addWidget = (widgetConfig) => {
        const newWidget = {
            ...widgetConfig,
            uniqueId: Date.now()
        }
        setWidgets([...widgets, newWidget])
    }

    const removeWidget = (uniqueId) => {
        setWidgets(widgets.filter(w => w.uniqueId !== uniqueId))
    }

    const clearCanvas = () => {
        if (confirm('Are you sure you want to clear all widgets?')) {
            setWidgets([])
        }
    }

    const saveReport = () => {
        try {
            localStorage.setItem(STORAGE_KEY, JSON.stringify(widgets))
            alert('Report saved to browser storage!')
        } catch {
            alert('Failed to save report.')
        }
    }

    const handleExport = () => {
        const html = generateHtmlReport(title, widgets)
        const blob = new Blob([html], { type: 'text/html' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `Report-${monthName}-${new Date().getFullYear()}.html`
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)
    }

    return (
        <div className="rs-app">
            <ReportToolbar
                title={title}
                onExport={handleExport}
                onClear={clearCanvas}
                onSave={saveReport}
            />

            <div className="rs-layout">
                <WidgetPalette onAdd={addWidget} />

                <div className="rs-canvas">
                    {widgets.length === 0 ? (
                        <div style={{ textAlign: 'center', padding: '50px', color: 'var(--text-muted)' }}>
                            <p>Canvas is empty.</p>
                            <p>Select widgets from the left to build your report.</p>
                        </div>
                    ) : (
                        <div className="dashboard-grid">
                            {widgets.map(widget => (
                                <WidgetCard
                                    key={widget.uniqueId}
                                    widget={widget}
                                    onRemove={() => removeWidget(widget.uniqueId)}
                                />
                            ))}
                        </div>
                    )}
                </div>
            </div>
        </div>
    )
}

export default ReportStudio
